usdigitalresponse/cpf-reporter

- .github/workflows/ci.yml
- .github/workflows/validate-deployment.yml
This PR fixes an issue from #26 in which a workflow step contained a syntax error when setting an environment variable. This is currently causing the [Deploy to Staging](https://github.com/usdigitalresponse/cpf-reporter/actions/workflows/deploy-staging.yml) workflow to fail, as seen [here](https://github.com/usdigitalresponse/cpf-reporter/actions/runs/7119662306/job/19385266574#step:5:12).
> Fix typo in validate-deployment workflow (issue #7)

- .github/workflows/validate-deployment.yml
Another follow-up to #26. This PR fixes an issue where an environment variable referenced in a workflow step was undefined.
> Add missing env var in validate-deployment workflow

- .github/workflows/deploy-staging.yml
Yet another follow-up fix for #26. This PR fixes an issue where the wrong path was being provided to the `tf-plan` job in the `Deploy to Staging` workflow, which is currently causing the job to fail.
This was the result of a simple typo (likely an autocomplete error on my part), so the change is minimal.
> Fix incorrect job input for API function artifacts path (issue #7)

- .github/workflows/ci.yml
This PR fixes an issue that is currently blocking certain PRs from running the entire Continuous Integration workflow to completion. The root problem was the presence of an `if:` job conditional that was evaluating to `false`, causing the "Plan Terraform" phase to be skipped. Since generating a successful Terraform plan is a requirement for PRs, they're effectively blocked from merging.
The problematic conditional doesn't seem to be doing anything useful, so it's been removed entirely.
> fix: remove tf-plan conditional in CI workflow

- api/db/migrations/20231209145213_add_subrecipient_and_project/migration.sql
- api/db/schema.prisma
- api/src/graphql/projects.sdl.ts
- api/src/graphql/subrecipients.sdl.ts
- api/src/services/projects/projects.scenarios.ts
- api/src/services/projects/projects.test.ts
- api/src/services/projects/projects.ts
- api/src/services/subrecipients/subrecipients.scenarios.ts
- api/src/services/subrecipients/subrecipients.test.ts
- api/src/services/subrecipients/subrecipients.ts
- api/types/graphql.d.ts
- web/types/graphql.d.ts
This change should complete the schema. Adds Subrecipient and Project, and their generated SDLs.
> feat: add Subrecipient and Project to the schema

- terraform/web.tf
This PR addresses an issue where requests to top-level routes like `/agencies`, `/organizations`, `/agencies/new`, etc. resolve a 404 response. Since React routing determines which view to serve based on the URI, this PR configures the CDN to serve `/index.html` (which loads the React app) whenever a request doesn't match an origin key (i.e. an S3 object). 
Caveat for this behavior: since the CDN can only differentiate between requests that match S3 object keys and those that don't, it is unable to determine whether an arbitrary path like `/maybe-this-exists` is valid as far as React is concerned. Although React's ability to serve the correct view (including potentially falling back to the "Not Found" view) is not impacted, it does mean that all requests to the CDN will respond with a 200 …
> Support SPA requests by routing 404 to /index.html

- web/src/App.tsx
Just like it says on the tin, this PR enables correlating Datadog RUM traces with upstream API traces, per [these instructions](https://docs.datadoghq.com/real_user_monitoring/connect_rum_and_traces/?tab=browserrum).
I believe that the headers that the Datadog RUM integration will automatically add to requests will be passed through as-is to the Lambda function event payload when invoked by API Gateway. If that doesn't appear to be the case, another (likely similarly small) PR may be necessary.
> Correlate RUM with API requests

- terraform/ecs_redwood_console.tf
This PR explicitly sets `tags = {}` on the `aws_ecs_task.console` resource definition in Terraform in order to allow default provider tags to populate the resource, as well as to avoid a permanent `{} -> null` change in plans.
> fix: Propagate ECS task tags from service

- terraform/api_gateway.tf
This PR is a follow up to #45, which updates API Gateway CORS configuration to allow tracing headers in API requests.
> Configure Access-Control-Allow-Headers for RUM

- api/src/directives/requireAuth/requireAuth.test.ts
- api/src/functions/graphql.ts
- api/src/lib/auth.ts
- package.json
- web/package.json
- web/src/App.tsx
- web/src/Routes.tsx
- web/src/auth.ts
- yarn.lock
This is a PR that includes the first two commits in #50 
The goal of this PR is to unblock work for the nav-bar creation while I'm working to finish the implementation of Passage auth.
> chore: add passage and redwood custom auth

- .github/workflows/ci.yml
This PR implements a fix for an issue that prevents reporting on QA and Terraform Plan outcomes when either/both of those CI jobs fail due to error. The problem is due to a misconfiguration in the conditionals for the reporting jobs in the CI workflow.
This is identical to the solution implemented recently for another repo that was having the same issue: https://github.com/usdigitalresponse/usdr-gost/pull/2378
> Fix skipped CI reports

- terraform/api_gateway.tf
Based on the discussion in Slack it appears that the issues we're seeing in staging is due to the lack of `auth-provider` being marked as an allowed header.
> fix: add auth-provider to allow header

- web/src/Routes.tsx
- web/src/auth.ts
Previously we copied a few routes from private-set into unauthenticated. However, this does not provide the appropriate data needed to support the upload page load. Hence this PR does:
1. Remove the duplicate routes
2. Ensure all routes (except login and not found) are within the private-set
> fix: remove duplicate routes

- api/src/graphql/agencies.sdl.ts
- api/types/graphql.d.ts
- web/src/components/Agency/AgencyForm/AgencyForm.tsx
- web/src/components/Agency/EditAgencyCell/EditAgencyCell.tsx
- web/src/pages/Agency/AgenciesPage/AgenciesPage.tsx
- web/types/graphql.d.ts
This PR fixes the issue where creating a new agency using the "Create New Agency" button doesn't display that agency, and the Agencies page remains empty.
1. `organizationId` is now being passed in correctly when creating/editing an agency
2. `organizationId` is initiated to the organization ID of the current user (currently `1`). This will be dynamic once authentication is implemented.
3. The agencies table now uses the current user's organization id (currently `1`) to display agencies only under that organization.
> Bugfix/CPF-74 - Creating a new agency not visible to the user

- api/src/lib/db.ts
- terraform/ecs_redwood_console.tf
This PR provides a solution for errors experienced getting the Prisma client to successfully connect to RDS Postgres in our Redwood console containers (running in ECS).
The current issue is that Prisma does not consider driver-specific environment variables (e.g. `PGHOST`, `PGPASSWORD`) when connecting to a database – Prisma will only use the default URL defined in `schema.prisma` or a `datasourceUrl` parameter passed during `PrismaClient` instantiation. At the moment, we only pass an explicit `datasourceUrl` parameter in Lambda environments (since Lambda doesn't support mounting secrets as environment variables) or when using RDS IAM authentication (which we haven't yet enabled in Staging, but would ultimately be the best option here); the ECS container environment running Redwood …
> Fix: Postgres auth in Staging console

- api/db/migrations/20240126151638_expenditure_category_nullable/migration.sql
- api/db/schema.prisma
- api/src/graphql/uploads.sdl.ts
- api/src/services/uploads/uploads.scenarios.ts
- api/src/services/uploads/uploads.test.ts
- api/src/services/uploads/uploads.ts
- api/types/graphql.d.ts
- scripts/seed.ts
- web/src/components/Upload/NewUpload/NewUpload.tsx
- web/src/components/Upload/UploadForm/UploadForm.tsx
- web/types/graphql.d.ts
Adds seed data for Expenditure Categories and makes expenditure_category nullable on Upload records.
This is because expenditure category will be derived from the uploaded workbook data, and this occurs _after_ the record has been created in the database.
> make expenditure_category nullable on an Upload

- api/src/lib/db.ts
- terraform/ecs_redwood_console.tf
This PR fixes problems using Prisma CLI commands in the Redwood ECS console, which were only partially resolved by #87 (which this PR largely reverts).
**Problem statement:** The Prisma CLI has no support for custom `PrismaClient` objects, meaning that the programmatic customizations/overrides present in `api/src/lib/db.ts` file's instantiation of `PrismaClient` have no effect when running `yarn rw prisma ...` commands. This is an unfortunate [limitation of Prisma](https://github.com/prisma/prisma/discussions/12336#discussioncomment-2361283) that is not particularly well-documented, despite [support for at-runtime customization](https://www.prisma.io/docs/orm/reference/prisma-client-reference#programmatically-override-a-datasource-url).
**Solution:** This PR updates the Terraform IAC for …
> Fix prisma CLI in Redwood ECS console

- terraform/functions.tf
#73
This PR adds CORS configuration to the "reporting data" S3 bucket to which the web application uploads files using a PUT request to a pre-signed S3 object URL. Since the object URL belongs to an S3 domain the remote resource (in this case, the S3 bucket), CORS configuration is required in order to allow browser scripts running on the website origin to make requests and read certain response data.
The CORS configuration is fairly permissive in this case, allowing GET, HEAD, PUT, and POST requests (DELETE is omitted on the assumption that object deletions would be handled by Lambda functions rather than through a presigned URL request made by the web-side). Additionally, all request headers are allowed, as are all [common S3 response …
> Fix: Add CORS config to reporting data bucket

- api/src/lib/aws.ts
- terraform/functions.tf
This PR fixes two issues with pre-signed S3 URLs:
1. A CORS misconfiguration, which currently omits `https://` from the allowed origin (website) domain name. This should have been included in #98.
2. An issue with the `PutObject` command used to configure pre-signed URLs for web-side upload. Currently, the command is configured without AES256 server-side encryption, which is a [requirement](https://github.com/usdigitalresponse/cpf-reporter/blob/4cf3d15cbdd6422d676ebbaac1b10fe49daf4803/terraform/functions.tf#L129-L131) of this S3 bucket. Without this fix, object uploads to S3 (regardless of CORS configuration) will continue to fail.
> Fix: S3 pre-signed uploads (PR #98 follow up)

- api/db/migrations/20240214193745_remove_user_validation_subrecipients_relations/migration.sql
- api/db/migrations/20240216211114_make_user_email_unique/migration.sql
- api/db/schema.prisma
- api/src/graphql/users.sdl.ts
- api/src/services/subrecipients/subrecipients.scenarios.ts
- api/src/services/subrecipients/subrecipients.ts
- api/src/services/uploads/uploads.scenarios.ts
- api/src/services/users/users.scenarios.ts
- api/src/services/users/users.test.ts
- api/src/services/users/users.ts
- api/types/graphql.d.ts
- scripts/seed.ts
- web/src/components/User/EditUserCell/EditUserCell.tsx
- web/src/components/User/UserCell/UserCell.tsx
- web/src/components/User/UsersCell/UsersCell.tsx
- web/types/graphql.d.ts
Updated the `User` model to have all fields required and removed `validated`, `invalidated` and `subrecipients` relations. Tests have been also updated to include all required fields and match changes in the schema.
**Changes to the schema break some existing functionality, mainly fetching and creating/updating users.**
> CPF-103 Update User model

- .github/workflows/deploy-staging.yml
AWS tokens are valid for a specific amount of time. If these tokens are generated during the build-step there is a risk that they will expire by the time they are being used for the terraform steps. The reason why they expire is because the build step currently takes longer than the AWS tokens validity duration.
This PR ensures that we make the `build` step a pre-requisite for AWS token generation so there is ample time for terraform steps to complete during the token validity duration.
> fix: generate aws-auth after build step

- api/src/services/users/users.scenarios.ts
- api/src/services/users/users.test.ts
- api/src/services/users/users.ts
- Create a common `currentUserIsUSDRAdmin` function to use across queries
- Modify `users`, `user` and `usersByOrganization` queries to use above function and, if user is not USDR admin, limit access only to other users in the querying user's organization
- Unit tests for the above changes
> Implement access controls for user queries

- api/src/graphql/users.sdl.ts
- api/src/services/users/users.scenarios.ts
- api/src/services/users/users.test.ts
- api/src/services/users/users.ts
**Note: the ticket asked for a mutation & resolver for updating a user, but these already existed, so I just updated them to match the ticket specs**
- Add a field for `isActive` to `UpdateUserInput` (input type already existed)
- Updated mutation resolver to validate on email, name, role, "good" agency id, logged in user role, logged in user org and new agency input
- Updated creation resolver to use the same validations as update (with the exception of new agency input, which isn't relevant for creation)
- Added unit tests for above
> Update user changes

- api/db/migrations/20240326182611_upload_validation_changes/migration.sql
- api/db/migrations/20240326192321_add_upload_validation_constraint/migration.sql
- api/db/schema.prisma
- api/src/graphql/uploadValidations.sdl.ts
- api/src/services/uploadValidations/uploadValidations.scenarios.ts
- api/src/services/uploadValidations/uploadValidations.ts
- api/src/services/uploads/uploads.scenarios.ts
- api/types/graphql.d.ts
- web/types/graphql.d.ts
* This PR includes _most_ of the changes requested to `UploadValidation` in this [issue](https://github.com/usdigitalresponse/cpf-reporter/issues/132)
* I have left the validated / invalidated fields in place for now, until the work is done to implement the logic based on `passed`, at which point they can be removed
* Per comment [here](https://github.com/usdigitalresponse/cpf-reporter/issues/132#issuecomment-2023683026), I am proposing to add a separate application layer validation for uniqueness of `uploadId` where `results` is null -- will implement that in a further PR to come
* Will also implement changes to `Upload` in a future PR -- they are causing some grief with type generators which I want to resolve separately
> UploadValidation database changes

- api/src/lib/auth.ts
- api/src/services/users/users.ts
- web/src/auth.ts
This PR emerged from going through the staging and local experience trying to figure out permissions discrepancies when rendering the `Uploads` list view and the `Users` page.
It fixes the following issues:
1. Any user that does not have a `USDR_ADMIN` role was unable to create/update users. Previously this could not be done because `agency` was not a property that was available on the `context.currentUser`.
2. The front-end was not rendering the /users page due to a permissions error for any user when `AUTH_PROVIDER=local`. This was because the RedwoodJS `<PrivateSet>` route-component requires there to be a `roles` attribute explicitly defined on the `User` object. For now, I have added an explicit casting of the existing `role` into a `roles` array, but we may want to consider a more …
> fix: rendering issues due to user permissions

- web/src/components/Upload/Uploads/columns.tsx
- web/src/components/Upload/UploadsCell/UploadsCell.tsx
- web/types/graphql.d.ts
This PR removes `validatedAt` and `invalidatedAt` references from the frontend and replaces them with required `passed` to determine whether the upload is valid or not.
> CPF-137 remove validatedAt and invalidatedAt, use passed instead

- api/src/lib/aws.ts
#139
As seen in the issue, this PR removes the expenditure category code from the S3 url for where the file is stored.
> fix: remove expenditure-code from s3 url

- terraform/functions.tf
This PR fixes a typo that is currently resulting in an incorrect Lambda layer ARN being referenced, which manifests in a permissions error:
> User: arn:aws:sts::357150818708:assumed-role/cpfreporter-cicd-20231201214238093500000001/GitHubActions is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:us-west-2:464622532012:layer:Datadog-Python312-x:91 because no resource-based policy allows the lambda:GetLayerVersion action
The role identified in the above error message is unimportant; no layer with an ARN of `arn:aws:lambda:us-west-2:464622532012:layer:Datadog-Python312-x:91` exists in Datadog's AWS account, which is the core problem. Specifically `Datadog-Python312-x` doesn't conform to Datadog's [documented](https://docs.datadoghq.com/serverless/aws_lambda/instal …
> Fix: Invalid Datadog layer ARN for Python lambdas

- terraform/functions.tf
#144 
The goal of this PR is to fix the following issue during terraform-apply:
https://github.com/usdigitalresponse/cpf-reporter/actions/runs/8575359827/job/23504325633
```
Error: updating Lambda Function (cpfreporter-cpfValidation) configuration: operation error Lambda: UpdateFunctionConfiguration, https response error StatusCode: 403, RequestID: aa5fe281-137b-4afc-b82a-1772d273352d, api error AccessDeniedException: User: arn:aws:sts::357150818708:assumed-role/cpfreporter-cicd-20231201214238093500000001/GitHubActions is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:us-west-2:464622532012:layer:Datadog-Python312-x:91 because no resource-based policy allows the lambda:GetLayerVersion action
with module.lambda_function-cpfValidation.aws_lambda_function.this[0 …
```
> fix: duplicate suffix in notification configuration

- terraform/functions.tf
#144 
This PR is attempting to resolve the following error when creating a `lambda_artifact-python` object in the existing lambda-artifacts S3 bucket. This is important in order to be able to deploy the new Python cpfValidation code.
```
aws_ecs_task_definition.console: Creating...
aws_s3_object.lambda_artifact-python: Creating...
aws_s3_object.lambda_artifact-cpfValidation: Modifying... [id=cpfValidation.07bca370db6319ce03a40b0b1c0599bc.zip]
aws_s3_object.lambda_artifact-excelToJson: Modifying... [id=excelToJson.7b4544585eee7c04a389cb50376[75](https://github.com/usdigitalresponse/cpf-reporter/actions/runs/8604013573/job/23580957301#step:16:76)9fb.zip]
aws_s3_object.lambda_artifact-graphql: Modifying... [id=graphql.1d3fd0f3db4f66fe2ce5bc04f4f8d75c.zip]
aws_ecs_task_definition.console: …
```
> fix: ensure cpfValidation lambda points to the python s3 object

- web/src/components/ReportingPeriodsCell/ReportingPeriodsCell.tsx
- web/src/components/Upload/Upload/Upload.stories.tsx
- web/src/components/Upload/Upload/Upload.tsx
- web/src/components/Upload/Uploads/columns.tsx
This PR:
- fixes `TypeError: Cannot read properties of null (reading 'code')` when accessing expenditureCategory.code if `expenditureCategory` is null
- adds "Not set" display when EC Category is not set in the Uploads table
> CPF-159 handle undefined EC Code in Upload Detail view

- api/src/services/uploads/uploads.test.ts
- api/src/services/uploads/uploads.ts
- web/src/components/Upload/NewUpload/NewUpload.tsx
- web/src/components/Upload/UploadForm/UploadForm.tsx
- When creating an `Upload`, create a "blank" associated `UploadValidation` with `results=null` and `passed=false`
- Add in the validations to the frontend mutation payload request (happy to remove these if reviewers would prefer; not sure if necessary but I tested with them and figured fine to leave in?)
- Add a unit test to ensure the validation is created
**UploadValidation present in DB after upload creation**
**UploadValidation present on result payload**
> Ensure an UploadValidation is created during creation of an Upload

- python/src/functions/validate_workbook.py
- python/src/lib/workbook_validator.py
- python/tests/conftest.py
- python/tests/src/lib/test_workbook_validator.py
This PR is a fix for #182 and a follow-up to #183. It avoids reading the entire Excel workbook (temporary) file into memory by removing a step where an `io.BytesIO` object is populated and provided to `openpyxl.load_workbook()`. Instead, we just provide the file directly to `openpyxl.load_workbook()`, which lets us benefit from using `openpyxl`'s [optimized read-only mode](https://openpyxl.readthedocs.io/en/stable/optimized.html?highlight=read-only#read-only-mode).
Additionally, this PR updates Python type annotations that referenced the `tempfile.TemporaryFile` function as a type (it is not, although it seems like it should be) to instead use [`typing.IO[bytes]`](https://docs.python.org/3/library/typing.html#abcs-for-working-with-io), which represents that the workbook file passed to …
> Fix: 182 Avoid reading workbooks into memory before validation

- terraform/functions.tf
#184
Fixes the following `Access Denied` error. The lambda function should have the ability to `get` JSON files however it currently only has the ability to `put` JSON files. This PR fixes it.
> fix: permissions for processValidationJSON function

- terraform/functions.tf
#190 
This PR fixes the following error noticed in [Datadog](https://app.datadoghq.com/logs?query=service%3Acpf-reporter%20&cols=host%2Cservice&context_event=AY7UIYgYAAA3JW_0RVM8cwAB&event=AgAAAY7omaPyeOtsswAAAAAAAAAYAAAAAEFZN29tYVZIQUFBRHFuMWxtRXRhR1FBRQAAACQAAAAAMDE4ZWU4OWItMTE4NC00ZTliLWJjMWUtYTAxNWE0Njc3ZGNh&fromUser=true&index=%2A&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Cdesc&viz=&from_ts=1713298485921&to_ts=1713299385921&live=true).
```
Handler error: PrismaClientInitializationError: 
Invalid `import_db.db.uploadValidation.findFirst()` invocation in
/var/task/api/dist/functions/processValidationJson/processValidationJson.js:82:66
79   uploadId,
80   passed
81 };
→ 82 const validationRecord = await import_db.db.uploadValidation.findFirst(
error: …
```
> fix: add database credentials to processValidationJson function

- api/src/functions/processValidationJson/processValidationJson.test.ts
- api/src/functions/processValidationJson/processValidationJson.ts
- python/src/functions/validate_workbook.py
- python/src/lib/workbook_validator.py
- python/tests/src/lib/test_workbook_validator.py
- Set project use code on upload at time of validation
- Includes changes to the python workbook validators to derive the project use code from the cover sheet, as well as JS changes to set the use code on the upload
- Unit tests for JS & python
> Set upload EC code

- terraform/web.tf
- Per conversation in Slack, the path pattern for deploy-config in Cloudfront is `/config/deploy-config`, which doesn't match the key for the file in S3 (since the full URL mapped to the origin is then `/config/config/deploy-config.js` and thus results in 404s to the resource
- This hard codes the path to `deploy-config.js`, which results in a full URL of `/config/deploy-config.js`. This is consistent with similar behavior in the GOST repo and should enable us to access the config
> Change cache path for deploy config

- web/src/components/Upload/NewUpload/NewUpload.tsx
- web/src/components/Upload/UploadForm/UploadForm.tsx
- After creating an upload, navigate to the page for that upload rather than back to the "all uploads" page
> Navigate to individual upload page after submission

- api/src/functions/processValidationJson/processValidationJson.test.ts
- api/src/functions/processValidationJson/processValidationJson.ts
- Only attempt to find & save expenditure category on an upload if there is a project use code returned in the validation JSON
> Only attempt to save expenditure category if there is a project use code

- api/src/lib/auth.test.ts
- api/src/lib/auth.ts
- web/src/pages/LoginPage/LoginPage.test.tsx
- web/types/graphql.d.ts
- Return currentUser based on the passage id retrieved through `event.requestContext.authorizer.jwt.claims.sub`
- Add `auth.test.ts` file to handle testing when passage ID is provided through jwt and when jwt is empty/null
Note: This functionality does not yet fully enable user authentication and should be verified when Passage is implemented.
> CPF-119 Passage API - getCurrentUser()

- api/src/functions/processValidationJson/processValidationJson.ts
- python/src/functions/validate_workbook.py
Fixes #201 
- This PR ensures that the S3 object keys are decoded correctly across both the `cpfValdiation` and `processValidationJson` lambda functions.
> fix: more url corrections across lambdas

- api/src/services/uploads/uploads.scenarios.ts
- api/src/services/uploads/uploads.test.ts
- api/src/services/uploads/uploads.ts
This PR implements the following functionality:
* Staff users can only see their own uploads (user.id == upload.uploadedById)
* Organization Admin and USDR Admin users can see any upload within their Organization (user.agency.organizationId == upload.agency.organizationId)
* Testing for all 3 roles (since organization admins and USDR admins have similar permissions, I added a reusable `uploadsBelongToOrganization()` function to follow DRY convention)
> CPF-214 Scope uploads by user role

- python/src/functions/validate_workbook.py
- python/src/lib/workbook_validator.py
- python/src/schemas/latest/schema.py
- python/tests/src/lib/test_workbook_validator.py
- This adds more detail to validator error messages, including the tab, row and column as well as the message
- The tab and the row were straightforward to get already, column was a bit trickier. I ended up mapping the columns from the google doc from @as1729 straight to the Pydantic `Field` definitions. This means that we can access them by field in the event of an error by mapping the error's `loc` property to the field def, and accessing the `json_schema_extra` which stores the column
- To make this work consistently, I also specified in the model configs that we want to loc by field name and not by alias (see [here](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.loc_by_alias)
> Update python errors schema

- web/src/Routes.tsx
- web/src/components/Navigation/Navigation.tsx
- web/src/components/Upload/UploadValidationButtonGroup/UploadValidationButtonGroup.tsx
- web/src/pages/Upload/UploadsPage/UploadsPage.tsx
For users who are not `USDR_Admin`, this PR:
- Hides the "Send Treasury/Audit Report" and "Download Empty Template" buttons on the Uploads page
- Hides the following tabs: Agencies, Users, Subrecipients, Reporting Periods and Organizations
- Hides the "Invalidate" and "Validate" buttons on the Upload Detail page
- Secures authenticated routes that are not upload routes and wraps pages in <PrivateSet /> to make them accessible only to USDR admins
To easily find every feature, component, or route that was hidden or secured as part of this ticket, you can search for `2024-05-13 Milestone` in the repository.
> CPF-213 Hide features 2024-05-13 milestone

- .github/release-drafter.yml
- .github/workflows/aws-auth.yml
- .github/workflows/deploy-production.yml
Relates to #225 
This PR adds a new "Deploy to Production" GitHub Actions workflow. As the name suggests, it deploys to production :) when a GitHub release draft is published (or when the workflow is manually triggered). It otherwise operates in a manner similar to the existing "Deploy to Staging" workflow (and differs in a manner similar to the ["Deploy to Production" workflow](https://github.com/usdigitalresponse/usdr-gost/blob/main/.github/workflows/deploy-production.yml) in the [usdigitalresponse/usdr-gost](https://github.com/usdigitalresponse/usdr-gost) repository). It runs the following steps:
- Validates that the contents of the deployment ref (a `release/`-prefixed tag) have all been merged to `main`.
- Builds deployment artifacts
- Authenticates with the target AWS environment's …
> Add production deployment pipeline

- web/src/components/Upload/UploadForm/UploadForm.tsx
#228 
Users can select any file locally. Here's an example of being able to select a `.png`.
Users can only select files with `.xlsm` extension.
> fix: ensure users can only upload .xlsm files

- python/src/lib/workbook_validator.py
- python/src/schemas/latest/schema.py
- python/tests/src/lib/test_workbook_validator.py
- web/src/components/Upload/UploadValidationResultsTable/UploadValidationResultsTable.tsx
#221
https://app.datadoghq.com/logs?query=service%3Acpf-reporter&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAY8vZ_rAuaptIAAAAAAAAAAYAAAAAEFZOHZaX3ZYQUFBbkloaFJWRHJ2clFBRQAAACQAAAAAMDE4ZjJmNjctZmFjMS00ODA1LThlZjQtOGRkZmJiNjczZmJi&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1714486414068&to_ts=1714487314068&live=true
Fixes the following error:
```
[ERROR] TypeError: Object of type ErrorLevel is not JSON serializable
Traceback (most recent call last):
  File "/opt/python/lib/python3.12/site-packages/datadog_lambda/wrapper.py", line 232, in __call__
    self.response = self.func(event, context, **kwargs)
  File "/var/task/src/lib/logging.py", line 54, in inner
    def inner(*args, **kwargs):
  File …
```
> fix: ability to dump validation errors into json without type-errors

- .github/release-drafter.yml
This PR brings some of the recent improvements to `.github/release-drafter.yml` configuration that were initially developed for the [usdigitalresponse/usdr-gost](https://github.com/usdigitalresponse/usdr-gost) repository:
- Make automatic versioning strategy less finicky and more automatic (based on https://github.com/usdigitalresponse/usdr-gost/commit/63703195a83738f54fff49b71091d889eb4db329)
- Add a `🗂️ Database Changes` section to release notes to call out release that contain migrations (based on https://github.com/usdigitalresponse/usdr-gost/commit/8d047d7d2b3a4b81b869b99d60c51be43f6950af)
> Release drafter updates

- .github/workflows/terraform-plan.yml
- terraform/production.s3.tfbackend
- terraform/production.tfvars
This PR configures Terraform state backend and input variables for targeting Production deployment environments. It also updates the `terraform-plan.yml` Github Actions workflow to provide the `github_repo_url` input variable to `terraform plan`.
> Configure Terraform for Production environment

- web/src/pages/LoginPage/LoginPage.tsx
- web/types/passage.d.ts
- Adds `<passage-login>` element that renders when auth_provider is set to passage
- Modifies JSX to include passage element types according to these docs: https://docs.passage.id/embedded-login/examples-by-framework/react#typescript-support
> CPF-122 Add Passage login element

- .github/workflows/deploy-production.yml
- .github/workflows/deploy-staging.yml
- .github/workflows/publish-terraform-plan.yml
- .github/workflows/terraform-plan.yml
This PR addresses two issues:
- Corrects the environment name config values in the `tf-apply` job of the `deploy-production.yml` workflow. These changes were mistakenly left out of #240.
- Implements `tf-summarize` instead of publishing the plaintext plan to GHA step summaries and PR comments. See https://github.com/usdigitalresponse/usdr-gost/pull/2966, which these changes are based on.
> Fix #240 environment settings & add `tf-summarize`

- .github/workflows/deploy-production.yml
This PR fixes a failing `tar` command that runs in the `deploy-production.yml` GHA workflow. The updated command ensures that the tarball is created with a single top-level directory, `./dist`, which contains the web-side build output.
> Fix `tar` command for building release artifact for web

- terraform/api_gateway.tf
- terraform/functions.tf
- terraform/production.tfvars
- terraform/staging.tfvars
- terraform/variables.tf
- terraform/web.tf
This PR makes two changes to Terraform configuration related to Passage:
1. Adds a missing `authorization_type = "JWT"` parameter to each GraphQL route entry in the API Gateway `integrations` map in Terraform. This is necessary because the [`terraform-aws-modules/apigateway-v2/aws` module](https://registry.terraform.io/modules/terraform-aws-modules/apigateway-v2/aws/2.2.2) will [default to `"NONE"`](https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/blob/dd6826c62909fe6aaf6761cb755b5124d876e80a/main.tf#L132) if this setting is not provided as explicit input (rather than, say, inferring the type from the related authorizer config). Currently, the API Gateway authorizer resource is created but never associated with any integration routes.
2. Makes Passage a requirement for …
> Fix authorizer config for APIGW integration routes & make Passage required

- api/db/schema.prisma
#246 
The above PR ended up having breaking changes for prisma. This PR fixes the error.
```
2024-05-07T19:32:14.742Z	0685460a-3db4-461b-a814-ced562abc1dd	ERROR	[dd.trace_id=1407637206256682088 dd.span_id=8046729419864637656] Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"PrismaClientInitializationError: Prisma Client could not locate the Query Engine for runtime \"rhel-openssl-3.0.x\".
This happened because Prisma Client was generated for \"debian-openssl-1.1.x\", but the actual deployment required \"rhel-openssl-3.0.x\".
Add \"rhel-openssl-3.0.x\" to `binaryTargets` in the \"schema.prisma\" file and run `prisma generate` after saving it:
generator client {
provider      = \"prisma-client-js\"
binaryTargets = [\"native\", …
```
> fix: prisma openssl version with node 20 upgrade

- api/src/lib/auth.ts
#244 
- Issue is `getCurrentUser` returns `null` for all passage users
This PR adds logging to figure out why that might be the case.
> chore: add logging around login failures

- terraform/production.tfvars
This PR simply updates Terraform variables for Production with the Passage app ID corresponding to that environment, removing the previous placeholder value.
> Add Passage app ID for Production

- api/src/lib/auth.ts
#234 
Some test code I wrote to make sure what type of logging captures custom objects.
```
const someObj1 = {
one: 'one',
}
logger.info(
'Identifying local authentication user from api-gateway event',
someObj1
)
const someObj2 = {
two: 'two',
}
logger.info(
someObj2,
'Identifying local authentication user from api-gateway event'
)
const someObj3 = {
three: 'three',
}
logger.info(`Test someobje ${someObj3}`)
const someObj4 = {
four: 'four',
}
logger.info({ custom: someObj4 }, 'foo bar someObj')
api | 14:17:55 🐛 Processing GraphQL Parameters
api | 14:17:55 🌲 Identifying local authentication user from api-gateway event
api | 14:17:55 🌲 Identifying local authentication user from api-gateway event 
api | 🗒 Custom
api | {
api |   "two": "two"
api | }
api | 14:17:55 🌲 Test someobje [object …
```
> fix: logging custom objects

- terraform/api_gateway.tf
Reverts usdigitalresponse/cpf-reporter#259
This didn't end up fixing the issue since Redwoodjs graphql initialization requires payload format 1.0.
https://app.datadoghq.com/logs?query=service%3Acpf-reporter&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAY9aZjK4xmymqwAAAAAAAAAYAAAAAEFZOWFaak03QUFBajFfeldtd1I0NVFBQwAAACQAAAAAMDE4ZjVhNjYtMzlkYy00MzFlLWIxY2UtNmM2MTFiNGNhYzE2&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1715205875587&to_ts=1715206775587&live=true
> Revert "chore: update payload version to 2.0"

- api/src/lib/auth.test.ts
- api/src/lib/auth.ts
#244 
This PR was needed because we were able to ensure through datadog logs ([here](https://app.datadoghq.com/logs?query=service%3Acpf-reporter&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAY9aS6HPZeptIAAAAAAAAAAYAAAAAEFZOWFTOFRCQUFEM2ZnY2VTU25kWmdBRQAAACQAAAAAMDE4ZjVhYTYtMzI2OS00YjUyLWE2OWUtM2FjZWE4MzlmZDI2&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1715145264800&to_ts=1715231664800&live=true)) that API Gateway is configured to use payload format version 1.0 while the passage code was expecting version 2.0 to retrieve the authorizer claim.
Initial attempt (#259) to upgrade the payload-format-version to 2.0 had failed due to other issues ([captured in datadog …
> fix: update passage code to use api gateway payload format v1.0

- python/src/schemas/latest/schema.py
- python/tests/conftest.py
- python/tests/src/lib/test_workbook_validator.py
- For unrequired fields, if we try to cast them to a `str` or other class when their value is `None`, we will get an error in validation
- This PR adjusts the schema such that every field where the `default=None` is marked as an `Optional` of whatever type the field was (many fields were already set up this way, but caught the ones that were not)
- I also added a unit test for the specific subrecipient case reported in the bug
> Mark unrequired fields as Optionals in schema

- api/src/lib/auth.ts
#3052
https://github.com/usdigitalresponse/usdr-gost/issues/3052
For some reason `error` object does not get logged into `custom` as seen in this datadog log: https://app.datadoghq.com/logs?query=service%3Acpf-reporter&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAY99B-lfrYO3hQAAAAAAAAAYAAAAAEFZOTlCLXJmQUFBMGhVeGN5NUpfSXdBRAAAACQAAAAAMDE4ZjdkMDctZWI1NC00NTVkLWIwMzktOTNiODZkMjgyYjM2&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1715788769367&to_ts=1715789669367&live=true
the error stack is explicitly logged
```
api | 11:41:22 🚨 Error getting current user. 
api | 🗒 Custom
api | {
api |   "event": {
api |     "httpMethod": "POST",
...
...
api |     "body": …
```
> chore: explicitly log error with user-auth

- api/jest.config.js
- api/setup-jest.ts
- api/src/lib/auth.test.ts
- api/src/lib/db.ts
Since a lot of Redwood internals expect `api/src/lib/db` to always be an instantiated Prisma client (ref - https://github.com/redwoodjs/redwood/issues/3707), this creates Jest setup that runs before all tests to initialize it.
> Create global setup for Jest tests so db is present

- api/db/migrations/20240521213042_reporting_period_changes/migration.sql
- api/db/schema.prisma
- api/src/graphql/reportingPeriods.sdl.ts
- api/src/graphql/users.sdl.ts
- api/src/graphql/validationRuleses.sdl.ts
- api/src/services/reportingPeriods/reportingPeriods.test.ts
- api/src/services/reportingPeriods/reportingPeriods.ts
- api/src/services/users/users.ts
- api/src/services/validationRuleses/validationRuleses.ts
- api/types/graphql.d.ts
- scripts/seed.ts
- web/src/components/ReportingPeriod/EditReportingPeriodCell/EditReportingPeriodCell.tsx
- web/src/components/ReportingPeriod/ReportingPeriod/ReportingPeriod.tsx
- web/src/components/ReportingPeriod/ReportingPeriodCell/ReportingPeriodCell.tsx
- web/src/components/ReportingPeriod/ReportingPeriodForm/ReportingPeriodForm.tsx
- web/src/components/ReportingPeriod/ReportingPeriods/ReportingPeriods.tsx
- web/src/components/ReportingPeriod/ReportingPeriodsCell/ReportingPeriodsCell.tsx
- web/src/components/ReportingPeriodsCell/ReportingPeriodsCell.tsx
- web/types/graphql.d.ts
This essentially is the same as the changes in [274](https://github.com/usdigitalresponse/cpf-reporter/pull/274), but after conversation with @as1729 we are not yet severing the link between reporting periods and organizations. We need to add the UI to collect organization preferences JSON, which will include a reporting period ID, and use that to link uploads to reporting periods. I will file a follow on ticket to remove the link between `organization` and `reporting period` when that is done.
> Reporting periods schema changes

- api/db/migrations/20240522032556_make_org_id_optional/migration.sql
- api/db/schema.prisma
- api/src/lib/constants.ts
- api/src/services/agencies/agencies.scenarios.ts
- api/src/services/agencies/agencies.test.ts
- api/src/services/agencies/agencies.ts
- api/src/services/expenditureCategories/expenditureCategories.test.ts
- api/src/services/expenditureCategories/expenditureCategories.ts
- api/src/services/inputTemplates/inputTemplates.test.ts
- api/src/services/inputTemplates/inputTemplates.ts
- api/src/services/organizations/organizations.scenarios.ts
- api/src/services/organizations/organizations.test.ts
- api/src/services/organizations/organizations.ts
- api/src/services/outputTemplates/outputTemplates.test.ts
- api/src/services/outputTemplates/outputTemplates.ts
- api/src/services/passage/passage.test.ts
- api/src/services/passage/passage.ts
- api/src/services/reportingPeriods/reportingPeriods.scenarios.ts
- api/src/services/reportingPeriods/reportingPeriods.test.ts
- api/src/services/reportingPeriods/reportingPeriods.ts
- api/src/services/users/users.test.ts
- api/src/services/users/users.ts
- scripts/onboardOrganization.ts
- scripts/seed.ts
- web/src/components/Organization/OrganizationPickListsCell/OrganizationPickListsCell.tsx
- web/src/components/ReportingPeriodsCell/ReportingPeriodsCell.tsx
#57 
#249 
The script replaces the existing `seed.ts` file with a more comprehensive onboarding script that is a bit more flexible and ensures that only net-new entities are created in the database. The script supports creation of:
- expenditure categories ( one time for all organizations)
- input templates (one time for all orgs)
- output templates (one time for all orgs)
- reporting periods ( one time for all organizations)
- Note: previously these were one-per-organization however, I have made the relationship `nullable` to be able to support the new standard.
- organizations
- agencies
- users
- passage user-creation and activation if not already setup
- All functions have unit tests. The script merely parses the arguments and passes directly to these functions.
- I also tested the …
> Adds a script to create new expenditure-categories, templates, reporting periods, organizations, agencies, and users

- Dockerfile
- README.md
- docker-compose.dev.yml
- redwood.toml
- web/public/deploy-config.js
As I was getting my local development environment to work with Docker, these are the changes I needed to make to be able to access `localhost:8910` from the host browser and for the seed code to work.
I also added some documentation to the README to get everything up an running in Docker.
> Enable docker for local development

- python/src/lib/workbook_validator.py
- python/src/schemas/latest/schema.py
- python/tests/conftest.py
- python/tests/src/lib/test_workbook_validator.py
Addresses https://github.com/usdigitalresponse/usdr-gost/issues/3053
I'm not sure what the best way to go about this. Using `field_validators` is the pydantic approach but I didn't want to create a different field validator for every type of field.
> add: update error messages and pydantic validators

- api/db/migrations/20240603182838_populate_organization_preferences/migration.sql
* Add current reporting period ID to organization preferences where it doesn't exist
* Ran this migration locally to test -- it worked on my local DB and set the value correctly!
> Add current_reporting_period_id to organization preferences where it doesn't exist

- api/src/services/uploads/uploads.scenarios.ts
- api/src/services/uploads/uploads.test.ts
- api/src/services/uploads/uploads.ts
- Users with "ORGANIZATION_STAFF" role can now view all uploads under their agency (previously they were only able to fetch their own uploads)
- Adjusted tests to include a scenario where an upload is from a different user but from the same agency
> CPF-289  Fetch all uploads under the same agency for "organization_staff" users

- python/src/lib/workbook_validator.py
- python/src/schemas/schema_V2024_04_01.py
- python/src/schemas/schema_V2024_05_24.py
- python/tests/conftest.py
- python/tests/src/lib/test_workbook_validator.py
Due to a macro in the worksheet, the A2 field stays in sync with B2 so we don't need to show the invalid error. We could actually remove all validation on A2 if we want too but I left it in for now to be safe.
https://github.com/usdigitalresponse/cpf-reporter/issues/305
> Adjust error messages

- python/src/schemas/schema_V2024_05_24.py
- Per #310 , this handles step 2 under "code snippets" and adds a new field, `output_column`, to the `json_schema_extra` of each `SubrecipientRow` field
> Add output_columns to json_schema_extra for SubrecipientRow fields

- api/db/migrations/20240613203006_subrecipient_schema_updates/migration.sql
- api/db/schema.prisma
- api/src/graphql/subrecipientUploads.sdl.ts
- api/src/graphql/subrecipients.sdl.ts
- api/src/services/subrecipientUploads/subrecipientUploads.scenarios.ts
- api/src/services/subrecipientUploads/subrecipientUploads.test.ts
- api/src/services/subrecipientUploads/subrecipientUploads.ts
- api/src/services/subrecipients/subrecipients.scenarios.ts
- api/src/services/subrecipients/subrecipients.test.ts
- api/src/services/subrecipients/subrecipients.ts
- api/types/graphql.d.ts
- web/types/graphql.d.ts
- Make some schema changes for `subrecipients` as needed for #310 
- Remove unneeded / unused fields (`certifiedAt`, `startDate`, `endDate`) from `subrecipient` table
- Add `status` column to `subrecipient` table, with enum values `ACTIVE` (default) or `ARCHIVED`
- Add a `SubrecipientUpload` table to store JSON data from subrecipient rows
- Related changes to GraphQL schema & resolvers (including removing some additional fields that were removed from DB schema but apparently not from GraphQL)
I smoketested this by:
- Running jest tests
- Running server locally & loading a few pages
- Build / API tests pass
> working on schema

- .github/workflows/qa.yml
- .vscode/extensions.json
- .vscode/settings.json
- python/src/functions/validate_workbook.py
- python/src/lib/output_template_comparator.py
- python/src/lib/workbook_validator.py
- python/src/schemas/project_types.py
- python/src/schemas/schema_V2024_04_01.py
- python/src/schemas/schema_V2024_05_24.py
- python/src/schemas/schema_versions.py
- python/tests/conftest.py
- python/tests/src/lib/test_workbook_validator.py
- scripts/onboardOrganization.ts
- scripts/passageAuth.ts
This PR ensures that our CI workflow correctly enforces our configured linter requirements for both `eslint` (JavaScript) and `ruff` (Python).
Changes to CI workflow:
- The "Lint python" job now fails when `ruff` detects an issue with Python code. Previously, an error message (`Process completed with exit code 1.`) would be listed as an annotation for the workflow, but the actual job would still (incorrectly) report as successful.
- The "Lint JavaScript" job now includes an additional step for running `eslint` against the `scripts/` directory. Previously, this directory was excluded from linter checks.
As part of these changes, all JavaScript/TypeScript and Python linter issues have been fixed, which provides a clean slate for these new enforcements.
Additionally, PR configures the …
> Enforce linter checks in CI

- api/src/services/users/users.ts
Fixes #284 
I can't reproduce the error locally, but that's likely because the DB is created differently in local vs staging. But looking at the [validator source](https://github.com/redwoodjs/redwood/blob/a3879f37a717105893455028027fe10f2890e853/packages/api/src/validations/validations.ts#L720), if the db isn't provided, it uses the default, which wouldn't work for staging. I think this should fix it in staging, but I'm not sure how to test that.
> Provide DB client to validator function when creating user

- api/src/lib/aws.ts
- api/src/services/uploads/uploads.test.ts
- api/src/services/uploads/uploads.ts
- scripts/deleteTestFiles.ts
#333
This PR ensures that we can delete the test upload files that partners have added in production. Running the script does the following:
1. Identifies all uploads for the organization (optionally filtered by IDs if passed in)
2. Deletes the `UploadValidation` record
3. Deletes the `Upload` record
4. Deletes the file from s3
Unit tests have been added and ran the script locally.
> feat: add ability to delete and reset testfiles

- api/src/lib/aws.ts
- terraform/ecs_redwood_console.tf
> fix: ensure terraform has the appropriate permissions

- api/src/services/uploads/uploads.test.ts
- api/src/services/uploads/uploads.ts
#333 
This PR will need to be reverted once the permissions issue of running `deleteTestFiles` script is fixed. However, for now we would need the ability to at least remove these records for our partners so they can begin upload production-ready input files.
> fix: remove ability to delete from s3 due to permissions issue

- python/src/lib/workbook_validator.py
- python/tests/src/lib/test_workbook_validator.py
* Expose subrecipients on ValidationResults in workbook_validator
* Putting this up by itself because I _believe_ that I'm not able to test S3 upload / the full flow locally yet? So my thought was to get this in staging, then upload a doc in staging and use it to test the "second piece" (reading the subrecipients key and saving them) via the workflow [here](https://github.com/usdigitalresponse/cpf-reporter/blob/02d37aa39770d98cb154ac73de0c4a779e6d7d8d/api/src/functions/processValidationJson/processValidationJson.ts#L52) -- but let me know if my understanding is incorrect!
> Expose subrecipients on ValidationResults in workbook_validator

- python/src/lib/workbook_validator.py
- python/src/schemas/schema_V2024_04_01.py
- python/src/schemas/schema_V2024_05_24.py
* Mapping each subrecipient to a JSON serializable object with `.model_dumps` so we can `json.dumps()` it in `validate_workbook.py`
> Make subrecipients into JSON explicitly

- api/src/functions/processValidationJson/processValidationJson.test.ts
- python/src/functions/validate_workbook.py
- python/src/lib/workbook_validator.py
- python/tests/src/lib/test_workbook_validator.py
* Expose version string on return payload from `validate_workbook` so that we can access it in `processValidationJson`
> Expose version string on return payload for validator

- api/src/functions/processValidationJson/processValidationJson.ts
- Use the `versionString` passed in to save on `SubrecipientUpload`
- If we can't cast the string provided to a `Version`, default to latest one
> Use real version passed in to save `SubrecipientUpload`

- api/src/functions/processValidationJson/processValidationJson.ts
* Save subrecipient information (`Subrecipient` and `SubrecipientUpload` records where the `createdAt` is within the upload's reporting period) to S3
* Tested this w/LocalStack and confirmed:
1. Able to put to S3 successfully: 
2. Able to download from S3 successfully: 
3. Downloaded was valid JSON:
> Save subrecipient information to S3

- web/src/pages/Upload/UploadsPage/UploadsPage.tsx
Allows USDR admins to trigger the sendTreasuryReport() mutation from the Uploads page.
> CPF-295 Trigger sendTreasuryReport mutation from the Uploads page

- terraform/treasury_generation_step_function.tf
There are deploy failures when attempting to deploy the latest step function changes:
```
aws_ecs_task_definition.console: Creating...
Error: creating Step Functions State Machine (cpfreporter-generate-treasury-report): InvalidDefinition: Invalid State Machine Definition: 'SCHEMA_VALIDATION_FAILED: The field "ProjectType" is not supported by Step Functions at /States/Parallel/Branches[0]/States/Generate Project 1A File/Parameters, SCHEMA_VALIDATION_FAILED: The field "ProjectType" is not supported by Step Functions at /States/Parallel/Branches[1]/States/Generate Project 1B File/Parameters, SCHEMA_VALIDATION_FAILED: The field "ProjectType" is not supported by Step Functions at /States/Parallel/Branches[2]/States/Generate Project 1C File/Parameters' …
```
> fix: remove unsupported ProjectType field

- api/src/graphql/agencies.sdl.ts
- api/src/services/users/users.ts
- web/src/Routes.tsx
- web/src/components/Navigation/Navigation.tsx
- Users with "organization_admin" role can now see Users and Agencies tabs and navigate to those pages
- Users with "organization_admin" role now have permissions to add/edit users and agencies
- Added specific role requirements to use createAgency and updateAgency mutations to match the logic we're using for createUser and updateUser mutations.
> CPF-380 Users and Agencies tabs visible for org users

- api/src/functions/processValidationJson/processValidationJson.ts
- python/src/functions/generate_treasury_report.py
- python/src/functions/subrecipient_treasury_report_gen.py
- python/src/lib/constants.py
- python/src/lib/treasury_generation_common.py
- python/src/schemas/schema_versions.py
- python/tests/conftest.py
- python/tests/src/lib/test_subrecipient_treasury_report_gen.py
- Add reporting data bucket as environment variables to the python lambdas
- Update project-lambda from S3 event structure to custom Payload structure
- Update both Subrecipient and Project Lambda to have a schema/type-defined payload structure for easier structure creation
- Add ability to upload Output template files from the graphql lambda
- Ensure Graphql and python lambdas have put/get object permissions for files within treasuryreports/output-templates and treasury reports… namespace of s3 bucket.
- Update tests based on the above changes for all the lambdas.
> chore: make tweaks to ensure step-function kick-off is consistent across file-generation lambdas

- scripts/seed.ts
Ran into the following error when setting up my dev environment from scratch:
```
Please define your seed data.
PrismaClientValidationError: 
Invalid `db.reportingPeriod.create()` invocation in
/home/node/app/scripts/seed.ts:105:54
102   outputTemplateId: lastOutputTemplateId,
103   organizationId: organizationRecord.id,
104 }
→ 105 const reportingPeriod = await db.reportingPeriod.create({
data: {
name: "First Reporting Period",
startDate: new Date("2024-08-13T15:04:42.144Z"),
endDate: new Date("2024-08-13T15:04:42.144Z"),
inputTemplateId: 1,
outputTemplateId: 1,
organizationId: 1,
~~~~~~~~~~~~~~
?   id?: Int,
?   validationRulesId?: Int | Null,
?   createdAt?: DateTime,
?   updatedAt?: DateTime,
?   uploads?: UploadUncheckedCreateNestedManyWithoutReportingPeriodInput,
?   projects?: …
```
> fix: ensure reporting period is able to be created correctly

- .github/workflows/build.yml
Fixes error in pipeline: https://github.com/usdigitalresponse/cpf-reporter/actions/runs/10423030086/job/28868977444
```
Run for $zipfile in $ARTIFACTS_PATH/*.zip; do
for $zipfile in $ARTIFACTS_PATH/*.zip; do
zip -ju $zipfile api/db/rds-global-bundle.pem
done;
shell: /usr/bin/bash -e {0}
env:
ARTIFACTS_KEY: api-48c854[2](https://github.com/usdigitalresponse/cpf-reporter/actions/runs/10423030086/job/28868977444#step:9:2)ced6b0636fc7c2f9cda0bb8af1150d994
BUILD_OUTPUT_PATH: /home/runner/work/cpf-reporter/cpf-reporter/api/dist
ARTIFACTS_PATH: /home/runner/work/cpf-reporter/cpf-reporter/api/dist/zipballs
/home/runner/work/_temp/de90ed[3](https://github.com/usdigitalresponse/cpf-reporter/actions/runs/10423030086/job/28868977444#step:9:3)0-5c57-43fd-9b2c-a87e41dcc8ff.sh: line 3: `$zipfile': not a …
```
> fix: build pipeline error - typo in bash command

- terraform/functions.tf
- terraform/treasury_generation_lambda_functions.tf
- terraform/treasury_generation_step_function.tf
#318 #320 
This PR is intended to do a few things in service of getting the Treasury report working (#83):
1. Unblock the deploy-pipeline by fixing [this](https://github.com/usdigitalresponse/cpf-reporter/actions/runs/10477450657/job/29019385583) permissions error
2. Update to kickoff `createArchive` lambda function via Step-function rather than SQS
3. Re-arrange code so lambda-functions related to treasury generation are in the `treasury_generation_lambda_functions.tf` file.
4. Adds permission for the `-graphql` lambda function to be able to download the `.zip` files
> chore: update terraform to kick-off archive from step functions

- terraform/treasury_generation_lambda_functions.tf
This PR is made as a response to testing the treasury generation step function in Staging. There were 403-forbidden errors relating to accessing the various files in s3. See [datadog](https://app.datadoghq.com/logs?query=service%3Acpf-reporter%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZGZMimHhHEkrgAAAAAAAAAYAAAAAEFaR1pNaXNsQUFDdW9jcmpqSG42S0FBRgAAACQAAAAAMDE5MTk5MzItM2E3Mi00ZGFmLWIyODItNWVlOTRkYmI0Mjdm&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1724851163253&to_ts=1724852063253&live=true) for specific error details.
The PR adds any missing permissions and edits any outdated definitions.
> fix: treasury reports generation s3 permissions

- python/src/functions/generate_treasury_report.py
- python/src/functions/subrecipient_treasury_report_gen.py
- python/src/lib/s3_helper.py
- python/src/lib/treasury_generation_common.py
- python/src/lib/workbook_utils.py
- python/tests/src/lib/test_subrecipient_treasury_report_gen.py
This PR was created to fix two things:
1. Typing errors within the python code related to `TemporaryFileWrapper`.
2. Issue with the usage of `json.dump`. Unclear why this wasn't generating test failures but the function call was raising a type-issue for a missing argument.
3. Consolidates the generation for s3 file keys for output files and stores it within `treasury_generation_common.py`. While this doesn't reduce the lines of code- I'm hoping that consolidating this reduces the chance of having a malformed object key anywhere else in the code as it appears to be recreated in multiple places.
> chore: refactor common code across lambda functions and fixes incorrect typing

- api/db/migrations/20240904164008_add_reporting_period_certification_model/migration.sql
- api/db/schema.prisma
- api/src/graphql/organizations.sdl.ts
- api/src/graphql/reportingPeriodCertifications.sdl.ts
- api/src/graphql/reportingPeriods.sdl.ts
- api/src/graphql/users.sdl.ts
- api/src/services/organizations/organizations.ts
- api/src/services/reportingPeriodCertifications/reportingPeriodCertifications.scenarios.ts
- api/src/services/reportingPeriodCertifications/reportingPeriodCertifications.test.ts
- api/src/services/reportingPeriodCertifications/reportingPeriodCertifications.ts
- api/src/services/reportingPeriods/reportingPeriods.ts
- api/src/services/users/users.test.ts
- api/src/services/users/users.ts
- Adds `ReportingPeriodCertification` model with a unique constraint on the combination of `organizationId` and `reportingPeriodId`
- Creates a database migration for the new model
- Adds `reportingPeriodCertifications` service, GraphQL schema, and associated tests
- Updates existing services and GraphQL schemas to include relations to reporting period certifications
Added a new model in `schema.prisma`:
```prisma
model ReportingPeriodCertification {
id                 Int             @id @default(autoincrement())
organizationId     Int
organization       Organization    @relation(fields: [organizationId], references: [id])
reportingPeriodId  Int
reportingPeriod    ReportingPeriod @relation(fields: [reportingPeriodId], references: [id])
certifiedById      Int
certifiedBy        User …
```
> CPF-408 Implement Reporting Period Certification Storage

- terraform/treasury_generation_lambda_functions.tf
Currently when the various lambda functions are attempting to retrieve non-existent files from s3, the client receives a 403-permission denied. This is because when files do not exist and the client does not have listObject permissions, then s3 will default to a permissions error.
Ideally we would like the functionality to fail gracefully with a 404 object not found for which the business-logic has mechanism to work around.
This PR ensures that the various lambda functions have the correct `listObject` permissions.
> fix: ensure that when files are missing in s3 the client receives a 404 instead of a 403

- terraform/treasury_generation_lambda_functions.tf
We are continuing to see 403 errors on the treasury report generation similar to [this](https://app.datadoghq.com/logs?query=service%3Acpf-reporter&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZHEsFz7yNzgHAAAAAAAAAAYAAAAAEFaSEVzRjdUQUFCbjFXUC1WUFFvLVFBQwAAACQAAAAAMDE5MWM0YjAtNzdlNi00NjZmLWIyNDQtYmNiM2JhMjY1MzA0&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1725578260233&to_ts=1725581860233&live=true)
The reason for this is that the `ListBucket` operation must be defined on a resource-name rather than a resource-name plus path. In order to define the specific path, I need to add it as a condition.
I was able to test this working in my personal AWS account so feel much more confident about this change …
> fix: ensure object-path is defined as a condition and not on the resource-name

- python/src/functions/generate_treasury_report.py
- python/src/functions/subrecipient_treasury_report_gen.py
- python/src/lib/s3_helper.py
- python/src/lib/treasury_generation_common.py
I initially expected `boto3` `ClientError` to have a `NoSuchKey` as part of the error-response. However, it appears that the code is "404" instead.
- Save the following code in a new file `s3_test.py`
- Run `python3 s3_test.py`
- Expect to see results with the following error message:
```
2024-09-17 07:54:42 [error    ] {'Code': '404', 'Message': 'Not Found'}
2024-09-17 07:54:42 [error    ] Expected to find an upload with key: foo/bar.txt
```
```py
from botocore.exceptions import ClientError
from mypy_boto3_s3.client import S3Client
from typing import IO, Optional, Union
from urllib.parse import unquote_plus
import tempfile
import structlog
import boto3
def get_logger(*args, **kwargs) -> structlog.stdlib.BoundLogger:
return structlog.get_logger(*args, **kwargs)
def …
```
> fix: updates code to 404 rather than NoSuchKey

- python/src/functions/generate_treasury_report.py
> fix: update to open file as binary

- web/src/components/Subrecipient/SubrecipientTableUploadLinksDisplay/SubrecipientTableUploadLinksDisplay.tsx
- web/src/components/Subrecipient/SubrecipientsCell/SubrecipientsCell.tsx
- Changed subrecipient upload links to lead to upload detail page (previously triggered download)
- Upload links now display "Upload {upload.id}" instead of "{upload.name}"
> CPF-447 Subrecipient upload links redirect to upload detail

- api/src/functions/processValidationJson/processValidationJson.ts
- python/src/functions/subrecipient_treasury_report_gen.py
- terraform/functions.tf
- terraform/treasury_generation_lambda_functions.tf
This PR fixes the following [datadog error](https://app.datadoghq.com/logs?query=host%3A169.254.121.205%20service%3Acpf-reporter%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&context_event=AZI0koHZAAAmlwrO7PZWPwAI&event=AgAAAZI0koBV8E6WUwAAAAAAAAAYAAAAAEFaSTBrb0haQUFBbWx3ck83UFpXUHdBSQAAACQAAAAAMDE5MjM0OWQtODM1OC00MzY4LTljZTktYjNhMWFiOTdiMTA1&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Cdesc&to_event=AgAAAZI0koBZ8E6WVAAAAAAAAAAYAAAAAEFaSTBrb0haQUFBbWx3ck83UFpXUHdBSgAAACQAAAAAMDE5MjM0OWQtODM1OC00MzY4LTljZTktYjNhMWFiOTdiMTA1&viz=&from_ts=1727458569333&to_ts=1727458869338&live=false)
```
Error saving subrecipients JSON file to S3: AccessDenied: User: arn:aws:sts::357150818708:assumed-role/cpfreporter-processValidationJson/cpfreport …
```
> Fix: Error related to saving subrecipients for treasury-report generation

- python/src/functions/generate_treasury_report.py
- python/src/functions/subrecipient_treasury_report_gen.py
Fixes #431
```
client.put_object(
TypeError: Strings must be encoded before hashing
```
When writing CSV or JSON files the `json` and `csv` libraries require a file-like object that is opened in text-mode. However, when uploading to S3, the `boto3` library requires all files to be opened in binary-mode.
The issue is resolved by doing the following:
1. Open the temporary file in text-mode and perform the appropriate CSV/JSON writes and close the file. Note: we set `delete_on_close=False` to ensure that the temporary file does not get deleted at this point.
2. Open the temporary file again in binary-mode specifically for the purpose of uploading the file to s3.
> fix: ensure CSV and JSON files are written as text but read as binary for s3 upload

- python/src/functions/create_archive.py
- python/tests/src/lib/test_create_archive.py
- `create_archive` lambda function is attempting to add the zip-archive to the root of `cpf-reporter` bucket.
- `create_archive` lambda function uploads the newly created zip-archive to `cpf-reporter/treasuryreports/{org_id}/{reporting_period_id}/report.zip` file.
> fix: add report.zip in the correct s3 path

- api/src/services/uploads/uploads.test.ts
- api/src/services/uploads/uploads.ts
- terraform/treasury_generation_step_function.tf
> chore: add success email as last step of treasury generation

- python/src/functions/create_archive.py
- python/tests/src/lib/test_create_archive.py
#431 
Resolves the following [datadog error](https://app.datadoghq.com/logs?query=host%3A%22arn%3Aaws%3Alambda%3Aus-west-2%3A357150818708%3Afunction%3Acpfreporter-cpfcreatearchive%22%20service%3Acpf-reporter%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&context_event=AZJJ8uZwAACDhiIzgxRTkQAL&event=AgAAAZJJ8uTNz8Kq9gAAAAAAAAAYAAAAAEFaSko4dVp3QUFDRGhpSXpneFJUa1FBTAAAACQAAAAAMDE5MjQ5ZmEtNTBhMy00MDRhLTk5ZTAtYjcxNzBiN2IzNGEx&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Cdesc&to_event=AgAAAZJJ8udNZ1QveAAAAAAAAAAYAAAAAEFaSkotUXFVQUFEazl1bngwaVpqOEFBQQAAACQAAAAAMDE5MjQ5ZmEtNTBhMy00MDRhLTk5ZTAtYjcxNzBiN2IzNGEx&viz=&from_ts=1727817208045&to_ts=1727817508686&live=false)
```
Failed to upload /tmp/tmpbc6embt1 to …
```
> fix: ensure encryption-config is passed to s3 upload-file

- web/src/Routes.tsx
- web/src/pages/Upload/UploadsPage/UploadsPage.tsx
> chore: enable send-treasury-report and subrecipients for organization admins

- web/src/components/Navigation/Navigation.tsx
> fix: ensure subrecipients option shows up in nav-bar

- web/src/components/Upload/UploadValidationButtonGroup/UploadValidationButtonGroup.tsx
As seen on the screenshots below this PR ensures that the Invalidate button is hidden for organization admins and only appears for USDR admins.
> chore: hide invalidate button from all users except usdr-admins

- api/src/services/uploads/uploads.scenarios.ts
- api/src/services/uploads/uploads.test.ts
- api/src/services/uploads/uploads.ts
> fix: ensure treasury generation payload has information for all projects

- api/src/functions/processValidationJson/processValidationJson.ts
#501 
There are some issues with having accurate subrecipient state when generating the treasury report and it looks like this could be due to a bunch of `async` transactions not completing on time prior to generating the list of valid subrecipients.
This PR does a couple of things:
1. Ensure that the loop to save subrecipients to the database is synchronous ensuring that the records are in the database prior to querying for them.
2. Separates the subrecipient logic into smaller functions to improve readability.
> refactor: logic flow for saving and maintaining subrecipient state

- .github/workflows/qa.yml
This PR is a fast-follow to #509, where we'd agreed to use Poetry to manage the `mypy` installation, but neglected to install poetry and incorporate it into the `mypy` execution. Currently the "Type-check python" job introduced in #509 is failing  ([example](https://github.com/usdigitalresponse/cpf-reporter/actions/runs/11977494138/job/33395495614?pr=518)) during the `actions/setup-python` step with the following error:
> Error: Unable to locate executable file: poetry. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
This PR fixes the issue by adding `pipx install poetry` prior to running `actions/setup-python` (which is a bit unintuitive, but is in …
> Fix: Missing poetry in "Type-check python" GHA job

- .github/workflows/qa.yml
Poetry could not find the `pyproject.toml` file because the working directory was not set to `python`, see:
https://github.com/usdigitalresponse/cpf-reporter/actions/runs/12210717069/job/34067127836?pr=516
Changes:
* adds the `working-directory` default so that the poetry install should work
* aligns the `mypy` step to the python setup version + poetry install step from the `test-python` job
> [fix][ci] adds `working-directory` default to the `mypy` job

- api/src/graphql/uploads.sdl.ts
- api/src/services/uploads/uploads.test.ts
- api/src/services/uploads/uploads.ts
- web/src/pages/Upload/UploadsPage/UploadsPage.tsx
Follow-up to: https://github.com/usdigitalresponse/cpf-reporter/pull/515
Changes:
* Adds a generate and send  (there will be no button to generate post-https://github.com/usdigitalresponse/cpf-reporter/pull/516)
* Adds a force-regenerate and send button
> [treasury-report][frontend] Add force regenerate button

- .github/workflows/qa.yml
The changed file step had `python/` prepended to the python files, but the working directory is already `python`
E: confirmed that this runs locally
```
$ poetry run mypy ${CHANGED_PY_FILES//python\/} --ignore-missing-imports
Success: no issues found in 2 source files
```
> [fix][ci] remove 'python/' from changed files that are passed in
