api/db/migrations/20231208211141_add_upload_expenditurecategory_and_uploadvalidation/migration.sql, api/db/schema.prisma, api/src/graphql/expenditureCategories.sdl.ts, api/src/graphql/uploadValidations.sdl.ts, api/src/graphql/uploads.sdl.ts, api/src/services/expenditureCategories/expenditureCategories.scenarios.ts, api/src/services/expenditureCategories/expenditureCategories.test.ts, api/src/services/expenditureCategories/expenditureCategories.ts, api/src/services/uploadValidations/uploadValidations.scenarios.ts, api/src/services/uploadValidations/uploadValidations.test.ts, api/src/services/uploadValidations/uploadValidations.ts, api/src/services/uploads/uploads.scenarios.ts, api/src/services/uploads/uploads.test.ts, api/src/services/uploads/uploads.ts, api/types/graphql.d.ts, web/types/graphql.d.ts
updated the schema for Upload, ExpenditureCategory, and UploadValidation and generated their SDL
=> feat: add Upload, ExpenditureCategory, and UploadValidation

api/db/schema.prisma, api/src/graphql/uploadValidations.sdl.ts, api/src/graphql/uploads.sdl.ts, api/src/services/subrecipients/subrecipients.scenarios.ts, api/src/services/uploadValidations/uploadValidations.scenarios.ts, api/src/services/uploadValidations/uploadValidations.ts, api/src/services/uploads/uploads.scenarios.ts, api/src/services/uploads/uploads.ts, api/types/graphql.d.ts, web/types/graphql.d.ts
Fixing a couple of typos that I noticed when pulling from main
=> Schema naming fixes

api/src/functions/cpfValidation/cpfValidation.scenarios.ts, api/src/functions/cpfValidation/cpfValidation.test.ts, api/src/functions/cpfValidation/cpfValidation.ts, api/src/functions/excelToJson/excelToJson.scenarios.ts, api/src/functions/excelToJson/excelToJson.test.ts, api/src/functions/excelToJson/excelToJson.ts, api/src/lib/aws.ts, terraform/functions.tf, web/src/Routes.tsx
Since the backend is not responsible for putting uploads into S3 (that is, it supplies a signed URL, and the frontend is what does the actual S3 Put), I think it makes sense to generate the JSON files using a Lambda function that responds to the S3 Put event.
I have added a function to do that. A couple of things are missing:
1.  we need a bit of terraform to configure the bucket to emit these events and set up the Lambda
2. we still need something to initiate a validation. Should that be in this function, or should it be separate?
3. can the UI have some kind of indicator that validation is still in progress? How do we notify when we're done?
=> add Lambda function to respond to S3 put events and add json files

.vscode/settings.json, api/db/migrations/20240301190538_add_passage_id/migration.sql, api/db/schema.prisma
1. Added `passageId` to the User model
2. Created index on the `passageId` field using `@@index` attribute
=> CPF-116 Add passageId field to User model

api/db/migrations/20240328204626_remove_validated_and_invalidated_at_fields/migration.sql, api/db/schema.prisma, api/src/graphql/uploadValidations.sdl.ts, api/types/graphql.d.ts, web/types/graphql.d.ts
* Remove `validatedAt`, `invalidatedAt`, and `invalidationResults` now that the frontend is using `passed`
=> Remove invalidated at and validated at fields

api/db/migrations/20240329180952_remove_notes_from_uploads/migration.sql, api/db/schema.prisma, api/src/graphql/uploads.sdl.ts, api/src/lib/persist-upload.js, api/types/graphql.d.ts, web/src/components/Upload/UploadForm/UploadForm.tsx, web/types/graphql.d.ts
* Remove notes field from type `Upload`, and remove frontend text field for notes
=> Remove notes field

web/src/components/Upload/UploadValidationResultsTable/UploadValidationResultsTable.stories.tsx, web/src/components/Upload/UploadValidationResultsTable/UploadValidationResultsTable.test.tsx, web/src/components/Upload/UploadValidationResultsTable/UploadValidationResultsTable.tsx
Closes #136 
This does the bare minimum asked for in the ticket - wasn't sure if I was supposed to wire anything up or do any additional styling, but please let me know if so! 
My first PR to this repo; I appreciate any feedback & apologize if I missed anything standard.
=> Upload Results Table component 

api/src/services/uploads/uploads.scenarios.ts
=> chore: refactor duplication in uploads test scenarios

api/src/lib/auth.ts, web/src/components/Agency/AgencyForm/AgencyForm.tsx, web/src/components/Upload/NewUpload/NewUpload.tsx, web/src/components/User/User/User.tsx, web/src/components/User/UserForm/UserForm.tsx, web/src/pages/Agency/AgenciesPage/AgenciesPage.tsx, web/src/pages/User/UsersPage/UsersPage.tsx
=> fix: relationship between users and organization

api/src/lib/aws.ts, api/src/services/uploads/uploads.ts
=> fix: incorrect orgID and removes duplicate method

web/src/components/Upload/UploadForm/UploadForm.tsx
=> try: removing multipart upload

web/src/components/Upload/UploadForm/UploadForm.tsx
=> Specify SSE header on S3 upload PUT request

terraform/functions.tf
=> Update graphql lambda permissions to allow uploads

terraform/functions.tf
=> fix: re-add mistakenly removed function trigger

python/src/lib/workbook_validator.py, python/tests/conftest.py, python/tests/src/lib/test_workbook_validator.py
=> Expect temp file input to validate function

api/src/graphql/uploads.sdl.ts, api/src/lib/aws.ts, api/src/services/uploads/uploads.test.ts, api/src/services/uploads/uploads.ts, api/types/graphql.d.ts, web/src/components/Upload/Upload/Upload.tsx, web/types/graphql.d.ts
#166 
Note - Per [discussion](https://usdigitalresponse.slack.com/archives/C056HNBK12T/p1712696555167389?thread_ts=1712622581.687019&cid=C056HNBK12T) in Slack, this is just the Download functionality.
=> Download file button/backend

terraform/functions.tf
=> add: graphql the ability to GET S3 objects

api/src/functions/processValidationJson/processValidationJson.test.ts, api/src/functions/processValidationJson/processValidationJson.ts, api/src/lib/aws.ts
#190 
1. When there is an error in getting object from S3
```
api | API listening on http://localhost:8911/
api | GraphQL endpoint at /graphql
api | 13:37:28 🌲 Server listening at http://[::]:8911
api | 13:37:42 🌲 incoming request GET xxx /processValidationJson?Records[0][s3][bucket][name]=cpf-reporter&Records[0][s3][object][key]=/uploads/1/2/3/16/test.json
api | ------------ USING LOCALSTACK ------------
api | endpoint: http://localhost:4566
api | 13:37:42 🚨 Error getting object from S3: NoSuchKey: The specified key does not exist. - key: /uploads/1/2/3/16/test.json
api | 13:37:42 🌲 request completed 195ms
api | 13:37:42 🚨 Handler error: Error: Error getting object from S3
```
2. When there is an issue with the validation record or it is missing
```
api | 13:40:00 🌲 incoming request GET …
```
=> Fix: JSON parsing issues in processValidationJson lambda function

api/src/functions/processValidationJson/processValidationJson.test.ts, api/src/functions/processValidationJson/processValidationJson.ts
=> fix: file-key string from s3

terraform/functions.tf
#190 
The previous PR #197 was missing the following policy statements that are added in this PR.
=> fix: adds missing permissions for processValidationJson to access database

python/src/functions/validate_workbook.py
=> fix: issue with python lambda downloading workbooks

python/src/schemas/latest/schema.py
=> fix: Adds support for 2024-04-01 and removes incorrect 2024-04-04

api/db/migrations/20240425200607_add_preferences_to_organization/migration.sql, api/db/schema.prisma, api/src/graphql/organizations.sdl.ts, api/types/graphql.d.ts, web/types/graphql.d.ts
* Add JSON preferences field to organization table
* Ran unit tests locally and smoketested loading organization page locally w/the seed organization
=> Add JSON preferences field to organization table

terraform/functions.tf, terraform/staging.tfvars, terraform/variables.tf
=> chore: enable local auth in staging

web/src/auth.ts, web/src/pages/LoginPage/LoginPage.tsx
=> fix: makes config name lowercase to match terraform

terraform/api_gateway.tf, terraform/staging.tfvars, terraform/variables.tf
=> chore: enable passage in staging

api/src/lib/auth.ts
=> chore: add logging to debug passage

terraform/api_gateway.tf
#244 
https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.proxy-format
=> chore: update payload version to 2.0

api/src/lib/auth.ts
=> chore: adds logging around passage permissions failures

api/src/lib/auth.ts
#244 
This is a follow-up PR for comments raised in #264
=> chore: add logging around the catch-block

api/src/lib/auth.ts, api/src/lib/db.ts
https://github.com/usdigitalresponse/usdr-gost/issues/3052
=> fix: ensure db is always a prismaclient

api/jest.config.js, api/setup-jest.ts, api/src/functions/graphql.ts, api/src/functions/processValidationJson/processValidationJson.ts, api/src/lib/auth.test.ts, api/src/lib/db.ts
=> fix: ensure all graphql requests start with initializing the database

python/src/lib/workbook_validator.py, python/src/schemas/latest/schema.py, python/tests/conftest.py, python/tests/src/lib/test_workbook_validator.py
Followup of https://github.com/usdigitalresponse/cpf-reporter/pull/276 to strip whitespaces for validation
=> chore: strip whitespaces for validation

python/src/lib/workbook_validator.py, python/src/schemas/schema_V2024_04_01.py, python/src/schemas/schema_V2024_05_24.py, python/tests/conftest.py, python/tests/src/lib/test_workbook_validator.py
Addresses https://github.com/usdigitalresponse/cpf-reporter/issues/294
Is there a good/easy way to test on the actual test files? I created test cases to verify this works but don't have a good way to test it on the actual files.
=> Add subrecipient validation

python/src/lib/workbook_validator.py, python/tests/src/lib/test_workbook_validator.py
Addresses https://github.com/usdigitalresponse/cpf-reporter/issues/294
=> chore: Update error descriptions

web/src/components/Upload/UploadValidationStatus/UploadValidationStatus.tsx, web/src/components/Upload/Uploads/columns.tsx
Updated the validation result text for invalid uploads on the Uploads tab (Uploads table) and the Upload Details page.
=> CPF-302 update validation result text

python/src/lib/workbook_validator.py
Addresses https://github.com/usdigitalresponse/cpf-reporter/issues/334
=> chore: read more columns in for project sheet

api/src/graphql/agencies.sdl.ts, api/src/services/agencies/agencies.ts, api/types/graphql.d.ts, web/src/components/Organization/OrganizationPickListsCell/OrganizationPickListsCell.tsx, web/src/components/Upload/NewUpload/NewUpload.tsx, web/src/components/Upload/UploadForm/UploadForm.tsx, web/types/graphql.d.ts
- Staff users
- only see their own agency in the dropdown
- their own agency is auto-selected
- Organization and USDR admins
- see all agencies under their organization
- their own agency is auto-selected
Before
After
=> CPF-313 Conditional agency dropdown

api/src/functions/processValidationJson/processValidationJson.test.ts, api/src/functions/processValidationJson/processValidationJson.ts, python/src/lib/workbook_validator.py, web/src/components/Upload/UploadValidationResultsTable/UploadValidationResultsTable.tsx
https://github.com/usdigitalresponse/cpf-reporter/issues/311
=> Address warning messages

web/src/components/Upload/UploadForm/UploadForm.tsx
https://github.com/usdigitalresponse/cpf-reporter/issues/341
For some reason, my local dev system isn't running right now, trying to figure it out but this code seems fairly straightforward...
=> Limit file size upload

python/src/functions/validate_workbook.py
Overlooked the value unpack here and we don't have unit tests for it :'( Encountered a bug while testing in staging
=> Fix value unpacking in validate_workbook

api/db/migrations/20240710175847_subrecipient_changes/migration.sql, api/db/schema.prisma, api/src/graphql/subrecipientUploads.sdl.ts, api/src/graphql/subrecipients.sdl.ts, api/src/graphql/uploads.sdl.ts, api/src/services/subrecipientUploads/subrecipientUploads.scenarios.ts, api/src/services/subrecipientUploads/subrecipientUploads.test.ts, api/src/services/subrecipientUploads/subrecipientUploads.ts, api/src/services/subrecipients/subrecipients.scenarios.ts, api/src/services/subrecipients/subrecipients.test.ts, api/types/graphql.d.ts, web/types/graphql.d.ts
- Add field `ueiTinCombo` to `Subrecipient` along with unique constraint
- Remove field `ueiTinCombo` from `SubrecipientUpload`
- Add link to `Upload` from `SubrecipientUpload`
=> Schema tweaks for Subrecipients and SubrecipientUploads

terraform/treasury_generation_step_function.tf
Fixes: https://github.com/usdigitalresponse/cpf-reporter/actions/runs/10187063630/job/28180969243
=> fix: add correct prefix to step function

README.md
This PR updates the local dev setup instructions to correctly perform db migration.
=> Update README local dev run list

python/src/functions/generate_treasury_report.py
Fixes [this issue](https://app.datadoghq.com/logs?query=service%3Acpf-reporter%20%40lambda_event.step_function.ProjectType%3A1B%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZIA6ITokeDNrgAAAAAAAAAYAAAAAEFaSUE2SVloQUFDSldLX0xKNHJFUXdBRQAAACQAAAAAMDE5MjAwZWMtMzhiMC00ZmE4LTg4MDctOGJjMzA3NTI3OGE0&fromUser=true&messageDisplay=inline&refresh_mode=sliding&sort=time&storage=hot&stream_sort=desc&viz=stream&from_ts=1726588524431&to_ts=1726592124431&live=true)
=> Add more errors, make output writeable

api/src/functions/processValidationJson/processValidationJson.ts, api/src/lib/aws.ts
=> fix: mistaken export and updated typing

python/src/functions/generate_treasury_report.py
=> fix: update output-file permissions to read-write instead of write-only

python/src/functions/generate_treasury_report.py, python/src/lib/workbook_utils.py
#431 
Fixes the following datadog error:
```
{
"id": "AgAAAZIQncYU8n0xuQAAAAAAAAAYAAAAAEFaSVFuY2ExQUFEZzhER3Y1Yk9ZSkFBQgAAACQAAAAAMDE5MjEwOWQtZTEwYi00MWVkLWI4MjktOGUwMDI3N2QxYmE4",
"content": {
"timestamp": "2024-09-20T18:07:08.308Z",
"tags": [
"aws_account:357150818708",
"function_arn:arn:aws:lambda:us-west-2:357150818708:function:cpfreporter-treasuryprojectfilegeneration",
"git.repository_url:https://github.com/usdigitalresponse/cpf-reporter",
"resource:cpfreporter-treasuryprojectfilegeneration",
"runtime:python3.12",
"source:lambda",
"env:staging",
"functionname:cpfreporter-treasuryprojectfilegeneration",
"account_id:357150818708",
"architecture:x86_64",
"dd_extension_version:55",
"git.commit.sha:60eadf0b6c139676f4ce87f935cab31ef68e74f3",
"memorysize:512",
"region:us-west-2", …
```
=> Fix: ensure CSV file is opened as string and not binary

python/src/functions/generate_treasury_report.py, python/src/schemas/schema_V2024_04_01.py, python/src/schemas/schema_V2024_05_24.py
Fix date output and don't output `None`s
https://github.com/usdigitalresponse/cpf-reporter/issues/436
=> chore: fix date output

python/src/functions/generate_treasury_report.py, python/src/schemas/custom_types.py, python/src/schemas/schema_V2024_04_01.py, python/src/schemas/schema_V2024_05_24.py
https://github.com/usdigitalresponse/cpf-reporter/issues/438
=> Serialize decimal with 2 decimal points

python/src/functions/generate_treasury_report.py, python/src/schemas/custom_types.py, python/src/schemas/schema_V2024_04_01.py, python/src/schemas/schema_V2024_05_24.py, python/tests/conftest.py
Follow steps in https://docs.pydantic.dev/latest/api/types/#pydantic.types.conint
=> chore: Replace conint and constr with new types

web/src/components/Upload/Uploads/Uploads.tsx, web/src/components/Upload/Uploads/columns.tsx, web/src/components/Upload/UploadsCell/UploadsCell.tsx
- Added "Reporting Period" column to the Uploads table
- "Reporting Period" column displays reporting period's name for every upload
- Filtering and sorting are enabled for the column
=> CPF-446 Add Reporting Period column to the Uploads page

python/src/functions/generate_treasury_report.py, python/src/functions/subrecipient_treasury_report_gen.py
#431 
This PR resolves more treasury file generation errors.
```
{
"id": "AgAAAZJIY50b4jSmRAAAAAAAAAAYAAAAAEFaSklZNTZwQUFCR1FDQWZWUTR3ZEFBQwAAACQAAAAAMDE5MjQ4NjMtYjRhMy00NDAyLWFmY2UtNTM4NjE3NjBiNDFm",
"content": {
"timestamp": "2024-10-01T14:02:20.827Z",
"tags": [
"aws_account:357150818708",
"git.commit.sha:dec099240b122315147f9b8223facc372e1504d0",
"git.repository_url:https://github.com/usdigitalresponse/cpf-reporter",
"version:dec099240b122315147f9b8223facc372e1504d0",
"functionname:cpfreporter-subrecipienttreasuryreportgen",
"runtime:python3.12",
"source:lambda",
"env:staging",
"resource:cpfreporter-subrecipienttreasuryreportgen",
"account_id:357150818708",
"function_arn:arn:aws:lambda:us-west-2:357150818708:function:cpfreporter-subrecipienttreasuryreportgen",
"architecture:x86_64", …
```
=> fix: ensure that json files are loaded in text-mode

python/src/functions/generate_presigned_url_and_send_email.py, terraform/treasury_generation_lambda_functions.tf, terraform/treasury_generation_step_function.tf
=> Fix - ensure the treasury generation step functions an invoke send-email lambda

terraform/treasury_generation_lambda_functions.tf
=> fix: ensure handler is correctly defined in lambda function

api/src/services/reportingPeriods/reportingPeriods.ts
- Moved read operations outside of transaction
- Increased transaction's timeout from 5s to 10s
Error details
```
PrismaClientKnownRequestError: 
Invalid `prisma.reportingPeriodCertification.create()` invocation in
/var/task/api/dist/services/reportingPeriods/reportingPeriods.js:171:49
168 if (!nextReportingPeriod) {
169   throw new Error("No next reporting period found");
170 }
→ 171 await prisma.reportingPeriodCertification.create(
Transaction API error: Transaction already closed: A query cannot be executed on an expired transaction. The timeout for this transaction was 5000 ms, however 5011 ms passed since the start of the transaction. Consider increasing the interactive transaction timeout or doing less work in the transaction.
at In.handleRequestError …
```
=> CPF-452 Fix transaction timeout

api/setup-jest.ts, web/src/components/ReportingPeriod/ReportingPeriods/columns.tsx
- Adds new column (ID) to reporting periods table
=> Feat: Reporting Period ID column

api/src/graphql/users.sdl.ts, api/src/services/uploads/uploads.scenarios.ts, api/src/services/users/users.test.ts, api/src/services/users/users.ts
- Resolve timing issue with promise chains in users.test.ts
- Update type references
=> Bug: flaky test 460

api/src/functions/processValidationJson/processValidationJson.ts, api/src/services/uploads/uploads.scenarios.ts, api/src/services/uploads/uploads.test.ts, api/src/services/uploads/uploads.ts
- Add missing unit tests for `getValidUploadsInCurrentPeriod` function
=> chore: add missing unit tests for getValidUploads function

api/src/graphql/subrecipients.sdl.ts, api/src/services/subrecipients/subrecipients.ts, web/src/components/TreasuryGeneration/DownloadTreasuryFiles/DownloadTreasuryFiles.tsx
#489 
This adds the front-end for #497
=> feat: add front end button to upload subrecipients

python/src/functions/generate_presigned_url_and_send_email.py, python/src/lib/s3_helper.py
Adds the timestamp of when the zip archive was last generated into the send treasury report emails.
=> [treasury-report] treasury archive timestamps in the emails
